sudo: required
services:
  - docker
before_install:
  - docker build -t nik0la84/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run nik0la84/react-test npm test -- --coverage
after_success:
  - docker build -t nik0la84/multi-client ./client
  - docker build -t nik0la84/multi-nginx ./nginx
  - docker build -t nik0la84/multi-server ./server
  - docker build -t nik0la84/multi-worker ./worker

  # login to the docker CLI and push images to docker hub
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_ID --password-stdin
  - docker push nik0la84/multi-client
  - docker push nik0la84/multi-nginx
  - docker push nik0la84/multi-server
  - docker push nik0la84/multi-worker
deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: multi-docker
  env: MultiDocker-env
  bucket-name: elasticbeanstalk-eu-central-1-743000549782
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY