sudo: required
services:
  - docker
before_install:
  - docker build -t nik0la84/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run nik0la84/react-test npm test -- --coverage
after_success:
  - docker build -t nik0la84/multi-client ./client
  - docker build -t nik0la84/multi-nginx ./nginx
  - docker build -t nik0la84/multi-server ./server
  - docker build -t nik0la84/multi-worker ./worker

  # login to the docker CLI and push images to docker hub
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_ID --password-stdin
  - docker push nik0la84/multi-client
  - docker push nik0la84/multi-nginx
  - docker push nik0la84/multi-server
  - docker push nik0la84/multi-worker